handler: math
dataset_path: "Mai0313/prm800k"
dataset_subset: default
dataset_split: train
question_key: problem
answer_key: answer
templating_parameters:
  template: "Return your final response within \\boxed{{}}. {problem}"

